### ISSUE TITLE
FYI: I've extracted the lsp-server boilerplate from rust-analyzer to a separate crate

### ISSUE THREAD

**Issue by matklad** [nix-community/rnix-lsp#1]
https://github.com/rust-analyzer/lsp-server

https://crates.io/crates/lsp-server

No docs or anything yet :)

**Comment by jD91mZM2** [comment]
Looks amazing, thanks! Here I was recently thinking "what happened to that gen_lsp_server thingy? should i switch to that"...

**Comment by jD91mZM2** [comment]
What's the point of creating a thread for stdout and stdin and communicate over crossbeam instead of reading them directly?

**Comment by matklad** [comment]
So that one can write tests that doesn’t do IO

**Comment by jD91mZM2** [comment]
On the `wip` branch I have migrated to this library :)

**Comment by matklad** [comment]
See also futures-based https://crates.io/crates/tower-lsp, which chooses pretty different tradeoffs.
