### ISSUE TITLE
[question] autocompletion

### ISSUE THREAD

**Issue by blaggacao** [nix-community/rnix-lsp#10]
Is `rnix-lsp` actually  supposed to autocomplete from `<nixpkgs>` (`$NIX_PATH`) imports?

If so I have it mis-configured. If not, why?

**Comment by jD91mZM2** [comment]
It's not supposed to, because I'm lazy. Feel free to send a PR.

**Comment by blaggacao** [comment]
Any effort might suffer better leverage when implementing a general available flake soecification.
