### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by Mic92** [nix-community/rnix-lsp#107]
It seems that @aaronjanse is a short of time or motivation to review the open pull requests. Should we allow other persons to join the project as a maintainer?

**Comment by aaronjanse** [comment]
That would be a good idea. I've been far too busy lately

**Comment by Mic92** [comment]
Btw there is also now https://github.com/oxalica/nil available. If project here stalls and it turns out that nil provides all features anyway, we could as well just archive this one.

**Comment by nyabinary** [comment]
Yea it looks stalled, nil should be bought over to the nix-community github repo

**Comment by Mic92** [comment]
I would actually leave the decision to oxalica where this project lives.

**Comment by Mic92** [comment]
Discussion weather we should archive this: https://github.com/nix-community/rnix-lsp/issues/112
