### ISSUE TITLE
flake.nix refers to a non-existent source

### ISSUE THREAD

**Issue by flokli** [nix-community/rnix-lsp#15]
I'm using rnix-lsp inside my home manager configuration:

```
let
  rnix-lsp = (import (pkgs.fetchFromGitHub {
    owner = "nix-community";
    repo = "rnix-lsp";
    rev = "274902aa662379fd30f12f0e310a2e738142da0e";
    sha256 = "1df74cnzzc6h21msld07615d74vxadrakr4xdn6f8q6lx3m8gbgd";
  })) {};
in {
  xdg.configFile."nvim/coc-settings.json".text = builtins.toJSON {
    languageserver.nix = {
        command = "${rnix-lsp}/bin/rnix-lsp";
        filetypes = ["nix"];
        "trace.server" = "verbose";
    };
  };
  # …
}
```

This seems to have become broken, because the commit in the NUR repository `flake.nix` is referring to doesn't exist (anymore?):

```
building the system configuration...
building '/nix/store/sn1d4gv876symdf9zb3sn141af304mzv-source.drv'...

trying https://gitlab.com/api/v4/projects/jD91mZM2%2Fnur-packages/repository/archive.tar.gz?sha=01b411a5de96cc484a00b861ad16dae901eed77d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
error: cannot download source from any mirror
builder for '/nix/store/sn1d4gv876symdf9zb3sn141af304mzv-source.drv' failed with exit code 1
```

I'm not sure how why this started happening now. `nix/sources.json` also seems to exist, but points to another NUR, which apparently is unused.

**Comment by jD91mZM2** [comment]
It's because I renamed the GitLab repository and apparently they don't set up redirects when you rename them, like GitHub does. We apparently also point to NUR in here to access nixpkgs-mozilla, which we could have done directly.

I'll update #14 and merge that, that'll fix things

**Comment by jD91mZM2** [comment]
Should be fixed now, and you can also build rnix-lsp using nix flakes again if you're using that feature

**Comment by flokli** [comment]
I updated the rev to latest master, but now the contract broke, as `default.nix` is not a function anymore, but a set (so I removed the `{}` after the `(import (pkgs.fetchFromGitHub { … }))`.

I can of course remove this, but I wonder if some documentation should be updated, and if this is intentional.

**Comment by jD91mZM2** [comment]
It used to be a function? I'm sorry for being oblivious, I haven't touched rnix-lsp in a while... What arguments did it take?

**Comment by flokli** [comment]
See my snippet from above - I called it with an empty attribute set.

**Comment by jD91mZM2** [comment]
Yeah alright so it was probably a pointless argument. Thanks for pointing it out, but I think I'll just let it be a breaking change, Nix keeps track of dependencies well enough anyway it's no biggie I think
