### ISSUE TITLE
is this how it should work?

### ISSUE THREAD

**Issue by breuerfelix** [nix-community/rnix-lsp#25]
Hey! glad i stumbled on this repo :) configured it with neovim nightly and builtin lsp.
this is how it looks: 
![image](https://user-images.githubusercontent.com/36931468/107190058-9bacf800-69ea-11eb-8365-0e2261d718f8.png)

at least i get an error message but it is always formatted like this. "error node at ....".  
Is there a way to turn on more specific error messages ? or is this currently the only error message possible with rnix lsp ?

cheers

**Comment by jD91mZM2** [comment]
Unfortunately, this is the only type of error message we have currently. Not sure why I haven't fixed it yet, but I think rnix-parser saves enough information. It could probably be tweaked fairly easily to [support more error types here](https://github.com/nix-community/rnix-lsp/blob/0a86e5b95ce4d8173fdc164c95dc5238b1d9a99e/src/main.rs#L378-L385)

**Comment by jD91mZM2** [comment]
Ended up having to bump a long chain of dependencies, but pull requests have been filed and things are in motion. You can compile the [`bump-rnix` branch](https://github.com/nix-community/rnix-lsp/tree/bump-rnix) and run it to get somewhat more interesting error messages

**Comment by breuerfelix** [comment]
i would love to test and give some feedback! BUT ... i am farily new to nixos, wenn i know that i would have to solve this with an overlay but i never wrote an overlay that compiles a package from scratch with a specify branch :D

do you have some overlay config to get me going here ?

**Comment by wiktorkuchta** [comment]
I'm also a noob, but I think that you won't easily build&install the `bump-rnix` branch with Nix because the flake files on this branch haven't been updated. If you just want the binary, build it with `cargo` (`nix-shell` should provide it to you).

**Comment by jD91mZM2** [comment]
Yeah the flake is broken right now, not sure if [`naersk`](https://github.com/nmattia/naersk) has problems with git dependencies or patches, or if I just borked something.

**Comment by breuerfelix** [comment]
finally i installed the branch with cargo and pointed my coc-vim to the binary (i have ditched neovim nightly lsp since at this stage it is not as good as coc ... too much error and mistages i had to solve at work) and it is amazing!

way better error message :) would love to have this merged! also i would love to contribute to add more to it but i really have to dig into this. maybe i will find some time for it in the future :)

**Comment by 573** [comment]
> 
> 
> Ended up having to bump a long chain of dependencies, but pull requests have been filed and things are in motion. You can compile the [`bump-rnix` branch](https://github.com/nix-community/rnix-lsp/tree/bump-rnix) and run it to get somewhat more interesting error messages

just for reference this is how you can use the branch: https://github.com/nix-community/rnix-lsp/issues/32#issuecomment-806611737

**Comment by Ma27** [comment]
This seems to be fixed on `master` and will be part of `0.2.0`.

(If I missed something, please ping me!)

**Comment by 573** [comment]
Have to reopen as I still get the OPs messages when using v0.2.4 (which is in nixos-unstable) as opposed to the better explained ones when using bump-rnix branch.

Example with bump-rnix:

>■ unexpected TOKEN_PAREN_CLOSE at 1941..1942, wanted any of [TOKEN_PAREN_OPEN, TOKEN_REC, TOKEN_CURLY_B_OPEN, TO■ unexpected TOKEN_PAREN_CLOSE at 1941..1942, wanted any of [TOKEN_PAREN_OPEN, TOKEN_REC, TOKEN_CURLY_B_OPEN, TO
