### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by zimbatm** [nix-community/rnix-lsp#3]
What is the best way to test this project out?

### vim

I found https://github.com/prabirshrestha/vim-lsp , maybe there are other LSP plugins out there.

Need to test this config:
```vim
if executable('rnix-lsp')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'rnix-lsp',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'rnix-lsp']},
        \ 'whitelist': ['nix'],
        \ })
endif
```

**Comment by jD91mZM2** [comment]
Do you want me to add these to the README, or should this be a place for anybody to submit their own instructions for various editors?

### NeoVim

LanguageClient-neovim: https://github.com/autozimu/LanguageClient-neovim

```vim
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rls'],
    \ 'nix': ['rnix-lsp']
\ }
```

- [My old dotfiles, might be outdated](https://gitlab.com/jD91mZM2/dotfiles/blob/96663e931ee4be7bce635ac3479de625ae231ba7/home/.config/nvim/init.vim#L111-116)

### Emacs

lsp-mode: https://github.com/emacs-lsp/lsp-mode

```elisp
  (add-to-list 'lsp-language-id-configuration '(nix-mode . "nix"))
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection '("rnix-lsp"))
                    :major-modes '(nix-mode)
                    :server-id 'nix))
```

**Comment by zimbatm** [comment]
the README will need to be updated at some point. maybe once the project is reaching beta maturity.

**Comment by prabirshrestha** [comment]
Also feel free to send the PR to https://github.com/mattn/vim-lsp-settings to automate installation of the language servers.

**Comment by jD91mZM2** [comment]
README updated. @zimbatm are there any plans to publish an early version of nixpkgs-fmt soon? I kind of feel like getting version 0.1.0 of rnix-lsp to crates.io :)

**Comment by zimbatm** [comment]
@jD91mZM2 done :) https://crates.io/crates/nixpkgs-fmt

**Comment by blaggacao** [comment]
The one for kakoune:

`~/.config/kak-lsp/kak-lsp.toml`

```toml
[language.nix]
filetypes = ["nix"]
roots = [".git"]
command = "rnix-lsp"

```

**Comment by Ma27** [comment]
AFAICS all configs that are shown here were added to the README. To me this currently seems sufficiently answered (please ping me if I'm wrong!).

Also, if somebody wants to share their editor-config with a different integration, feel free to open a PR :)
