### ISSUE TITLE
[feature request] nixpkgs goto definition

### ISSUE THREAD

**Issue by aaronjanse** [nix-community/rnix-lsp#31]
It would be cool to be able to "goto definition" for packages and maybe even goto for nixos options. This might require that the edited expression is a Nix Flake.

I have a break from university this week, so I'm willing to put a lot of effort into implementing this. I thought it would be good to document the feature request here in case there's a huge roadblock I'm missing etc, if the implementation is already in progress, or if there's another reason to not do this.

Cheers :-)

**Comment by Ma27** [comment]
@aaronjanse I guess it may be somehow possible to use the logic from e.g. builtins.unsafeGetAttrPos.

**Comment by aaronjanse** [comment]
Replaced by https://github.com/nix-community/rnix-lsp/issues/41
