### ISSUE TITLE
What happened with maintainer?

### ISSUE THREAD

**Issue by remimimimi** [nix-community/rnix-lsp#39]
From time to time I watch for updates in the development of nix lsp, but since March the maintainer has been inactive. Has something happened with him?

**Comment by aaronjanse** [comment]
https://www.redox-os.org/news/open-source-mental-health/

**Comment by domenkozar** [comment]
He will be missed. There are no words to describe such events :( 

I'm going to close this issue.

**Comment by zimbatm** [comment]
The best hommage is to keep his work alive. The project will have a new maintainer this week.
