### ISSUE TITLE
Incremental edit handler not detecting edits at end of file

### ISSUE THREAD

**Issue by aaronjanse** [nix-community/rnix-lsp#42]
Steps to reproduce:
1. Add `error!` logging to print the `content` calculated by the incremental edit handler
1. Create a file with just `1 + 2`
2. Delete all the text in the file (ctrl-a, backspace)
3. Write `3 + 4`
4. Observe that no matter what we type, the incremental edit handler returns an empty string

This can also be reproduced by appending any file with a newline followed by new text. The text appended to the file is not detected.

I suspect this is due to a loop that iterates over the length of the original file, which I assume misses edits that happen after the end of a file:

https://github.com/nix-community/rnix-lsp/blob/e1ec7a064cdaa9a362561ab4a14dee60a4f84fbf/src/main.rs#L249

**Comment by Ma27** [comment]
Ouch, thanks for the report and the summary! I'll try to take a look soon. Also, I'll try to add a test-suite here as I'm a little bit afraid atm to get regressions I've already seen when experimenting with this.
