### ISSUE TITLE
aarch64-darwin support

### ISSUE THREAD

**Issue by DieracDelta** [nix-community/rnix-lsp#71]
`rnix-lsp` does not build for `aarch64-darwin`. This is being caused for two reasons: 
- `nixUnstable` in 21.05 right now is broken on nixpkgs for `aarch64-darwin`.
- The pinned `naersk` does not have an `aarch64-darwin` output.

`nixUnstable` can be fixed to build for `aarch64-darwin` by disabling a test on `aarch64-darwin`. This is already merged into nixpkgs master but it hasn't been backported. We could potentially just add in an override? Or switch nixpkgs to depend on some "known to build" nixpkgs master commit.

If we bump `naersk` then it will include `aarch64-darwin` support.

For what it's worth, I have rnixlsp building for aarch64-darwin [here](https://github.com/DieracDelta/rnix-lsp/tree/mbp-fix). But I'm following master nixpkgs and naersk.

**Comment by aaronjanse** [comment]
@Ma27 Disabling the test and bumping versions sounds worthwhile for me. Should I make a PR to do so?

**Comment by Ma27** [comment]
AFAICS @DieracDelta only had to bump a few inputs, correct? We should switch to 21.11 anyways since 21.05 is dead.
