### ISSUE TITLE
Document Integration For Doom Emacs

### ISSUE THREAD

**Issue by Lord-Valen** [nix-community/rnix-lsp#97]
### Description

[Doom Emacs now has a flag for nix lsp](https://github.com/doomemacs/doomemacs/issues/6592#issuecomment-1194234477) so it should be documented in the README for Doom users.

```elisp
;; init.el

(doom! 
       ;; ... 
       :lang
       (nix +lsp)
       ;; ...
       )
```

**Comment by aaronjanse** [comment]
Thanks! Would you mind making a PR?
